# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180124_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_other',
        ),
    ]
